### ISSUE TITLE
Errors are part of the domain

### ISSUE THREAD

**Issue by aschrijver** [NeutrinoCorp/ddderr#1]
First of all: I am new to Go, so there may be an obvious and intuitive way implement what I'm missing in ddderr (but if there is, the examples might be extended to demonstrate it).

> Domain errors are part of the domain.

I still miss this in the examples. Okay, the error has an `IsDomain()` func, but other than that it isn't self-describing. I need to look at the strings within the error struct to deduce the nature of the domain error.

Consider https://khalilstemmler.com/articles/enterprise-typescript-nodejs/functional-error-handling/

Here errors are types that are defined explicitily within the '/domain' part of the project e.g. `UsernameTakenError`, `InsecurePasswordError` fitting for a User Management domain (even the `Error` suffix is often not needed in 'ubiquitous language' e.g. in an e-commerce domain you might have `GiftCardExpired` representing a domain error).

I am looking at DDD in Go based on the great Wild Workouts blog series, and here are examples of implementing true domain errors, e.g. [`CantRescheduleBeforeTimeError`](https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/blob/master/internal/trainings/domain/training/reschedule.go#L18). Their error handling might be further improved with ddderr and concepts explained in [Failure is your domain](https://middlemost.com/failure-is-your-domain/).

**Comment by aruizeac** [comment]
Hello,

Now with the latest release I think I just solved this issue.

The latest release lets you define an error `status`; this means that now you are able to label any kind of error using the `SetStatus` method. Thus, now you will be able to identify specific errors and it also integrates seemly with HTTP responses (based on the RFC spec).

**Comment by aschrijver** [comment]
Wonderful. Thank you!
